### ISSUE TITLE
Draw images for PlantUML markup reachable via URL?

### ISSUE THREAD

**Issue by mpdude** [plantuml/plantuml-server#4] opened 2013-11-22 14:05 UTC
It would be great if we could pass the PlantUML server an URL to a markup file as an URL parameter and get the image in return.

That way, I could put .puml files somewhere in my repo.

Then, my documentation .md files could point to something like `http://www.plantuml.com/imageForUrl?url=..urlencoded_URL_of_the_raw_version_of_the_markup_file...` and embed the image rendered by the server.

... at least until GitHub supports PlantUML nativaly :)

As an extra bonus, a second parameter could choose which `@startuml...@enduml` section to pick from the source file in case there are more than one.

Does that make sense?

**Comment by erossignon** [comment] 2015-06-25 07:14
![Test]( http://www.plantuml.com/plantuml/proxy?idx=0&src=https://raw.github.com/maximesinclair/for-testing-purpose/master/twodiaguml.puml)

**Comment by maximesinclair** [comment] 2015-06-25 20:52
Yes, it works !

**Comment by fuhrmanator** [comment] 2015-12-18 20:43
This works with one caveat (a problem with GitHub). The markdown engine renders the 

    ![blah](http://www.plantuml.com/plantuml/proxy?idx=0&src=https://raw.github.com/maximesinclair/for-testing-purpose/master/twodiaguml.puml) 

as an image in the camo.githubusercontent.com web site (image cache). Open this image in a new tab to see an example: ![blah](http://www.plantuml.com/plantuml/proxy?idx=0&src=https://raw.github.com/maximesinclair/for-testing-purpose/master/twodiaguml.puml)

The problem is that this cache won't be updated unless the URL to the image changes. GitHub assumes images to be static, whereas PlantUML images drawn via the proxy are not. 

Prior to the proxy service feature, I was using the PlantUML **!includeurl URL-to-source.puml** (language) feature. A work-around to the GitHub cache problem is to toggle some **redundant** information in the URL (change the URL without changing the file specification), as explained below. 

https://github.com/fuhrmanator/course-activity-planner/commit/45fd5d86153003092593cd028f3fded1eb60917c

With the proxy service, this workaround might be to add/remove "idx=0&" in the URL.

**Comment by baguio** [comment] 2017-03-02 20:12
The official word about Github's CDN caching affecting dynamically generated images is here:  
https://github.com/github/markup/issues/224#issuecomment-48532178

The fix should be changing the cache headers here, where image caching is being forced:  
[Line 93 at DiagramResponse.java](https://github.com/plantuml/plantuml-server/blob/master/src/main/java/net/sourceforge/plantuml/servlet/DiagramResponse.java#L93)

**Comment by arnaudroques** [comment] 2017-03-02 20:53
Yes, by default, PlantUML server sends some Cache-Control/public header for images. This makes sense for text diagram without !include.

We cannot simply remove it for every served image, but we could improve this behaviour:
For example, if we detect some !include directive in the diagram, we could change the header to Cache-Control/no cache.

This is something we have already implemented very basically, see
https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/StringUtils.java#L333

So you can even check now is the following URL gives the right HTTP header
http://www.plantuml.com/plantuml/png/AqijAixCpmC0

**Comment by baguio** [comment] 2017-03-02 23:23
How about adding a `revision` tag to the specification?  
`@startuml revision 89`

That way, if a diagram
* Includes impredictable changes (e.g. Hosted on Github) AND
  * Includes a `revision` puml tag and `Etag` http header (Github does) OR
  * Includes a `Last-Revision` http header
that data get attached to the resulting file
* `Etag` and `revision` number get concatenated and attached to the image as the new `Etag` OR
* `Last-Revision` gets attached to the image

That way Github knows when to grab the new file, files stay as cacheable as possible, and PUML changes are more noticeable (human-readability: any person can check if a diagram has changed in the least)

**Comment by asd-and-Rizzo** [comment] 2017-03-03 07:57
I have closed duplicate of this issues which I have created with next text:
```
Given I have public link to text file with uml on gitlab or github, I may paste link into plantuml server and get image.

It would be either reasonable to create issue on github and gitlab to render plantuml inside their web interfaces, like these where done for some other kinds of text - e.g. 2d/3d models.
```

**Comment by arnaudroques** [comment] 2017-03-03 08:07
The option `revision `tag is a good idea.
We are going to think about it.
We will probably do it lightly differently (that is, providing a special line `!pragma revision 89` ), but the result would be the same.
We'll post a message here when http://plantuml.com/plantuml will include this
Thanks for the suggestion!

**Comment by arnaudroques** [comment] 2017-03-08 20:44
We have put a new version of the online server http://plantuml.com/plantuml

The code is not published yet, but it will be in few days/weeks.

This version now handles correctly HTTP Headers `Cache-Control/Etag/Expires/Last-Modified` and is able to send a `304 Not Modified` response when the request contains `If-Modified-Since/If-None-Match`
We did not include any `Last-Revision` header because we did not find any material about this HTTP header. Is this a standard one ? Any pointer will be welcome.

This way, integration with Github/Gitlab should be improved. Do not hesitate to make feedback about this.
Thanks,

**Comment by baguio** [comment] 2017-03-08 21:17
My bad, i was talking about `Last-Modified`.
Is the `revision` tag still possible?

**Comment by arnaudroques** [comment] 2017-03-08 21:25
Yes, it's still possible.
You will have to use something like:
```
@startuml
!pragma revision 89
...
@enduml

```
`Etag `header will be modified when the revision number will be.

**Comment by hqzxjczx** [comment] 2019-05-28 16:19
according the post [Markdown native diagrams with PlantUML | Andreas' Blog](https://blog.anoff.io/2018-07-31-diagrams-with-plantuml/), we can set the 'cache' params to be 'no', so when the reffer file is committed, the reffered uml image will be update too.

**Closed** 2023-07-15 20:29 UTC
Labels: feature-request
